In [2]:
import pandas as pd
import os
import csv
from collections import Counter
DATA_DIR = 'data/'
POPULATION_DATA_DIR = DATA_DIR + 'population/'
PROCESSED_DATA_DIR = DATA_DIR + "processed/"

## Merge input files

In [2]:
files = os.listdir(POPULATION_DATA_DIR)
census_files = [file for file in files if '.xlsx' in file]
census_files

['1861.xlsx',
 '1836.xlsx',
 '1898.xlsx',
 '1877.xlsx',
 '1882.xlsx',
 '1894.xlsx',
 '1857.xlsx',
 '1841.xlsx',
 '1840.xlsx',
 '1856.xlsx',
 '1895.xlsx',
 '1883.xlsx',
 '1876.xlsx',
 '1837.xlsx',
 '1860.xlsx',
 '1884.xlsx',
 '1892.xlsx',
 '1851.xlsx',
 '1847.xlsx',
 '1888.xlsx',
 '1867.xlsx',
 '1871.xlsx',
 '1870.xlsx',
 '1889.xlsx',
 '1866.xlsx',
 '1846.xlsx',
 '1850.xlsx',
 '1893.xlsx',
 '1885.xlsx',
 '1845.xlsx',
 '1853.xlsx',
 '1890.xlsx',
 '1869.xlsx',
 '1886.xlsx',
 '1849.xlsx',
 '1873.xlsx',
 '1865.xlsx',
 '1864.xlsx',
 '1872.xlsx',
 '1848.xlsx',
 '1868.xlsx',
 '1887.xlsx',
 '1891.xlsx',
 '1852.xlsx',
 '1844.xlsx',
 '1859.xlsx',
 '1875.xlsx',
 '1863.xlsx',
 '1843.xlsx',
 '1855.xlsx',
 '1879.xlsx',
 '1896.xlsx',
 '1838.xlsx',
 '1880.xlsx',
 '1881.xlsx',
 '1839.xlsx',
 '1878.xlsx',
 '1897.xlsx',
 '1854.xlsx',
 '1842.xlsx',
 '1862.xlsx',
 '1835.xlsx',
 '1874.xlsx',
 '1858.xlsx']

In [3]:
df_example = pd.read_excel(POPULATION_DATA_DIR+'1861.xlsx', index_col=0)

df_census = pd.DataFrame(columns=df_example.columns)
for filename in census_files:
    print(f"Read file: {filename}")
    df_year = pd.read_excel(POPULATION_DATA_DIR+filename, index_col=0)
    df_year['annee'] = filename.replace('.xlsx','').replace('_', '')
    df_census = df_census.append(df_year)
print(len(df_census))

Read file: 1861.xlsx
Read file: 1836.xlsx
Read file: 1898.xlsx
Read file: 1877.xlsx
Read file: 1882.xlsx
Read file: 1894.xlsx
Read file: 1857.xlsx
Read file: 1841.xlsx
Read file: 1840.xlsx
Read file: 1856.xlsx
Read file: 1895.xlsx
Read file: 1883.xlsx
Read file: 1876.xlsx
Read file: 1837.xlsx
Read file: 1860.xlsx
Read file: 1884.xlsx
Read file: 1892.xlsx
Read file: 1851.xlsx
Read file: 1847.xlsx
Read file: 1888.xlsx
Read file: 1867.xlsx
Read file: 1871.xlsx
Read file: 1870.xlsx
Read file: 1889.xlsx
Read file: 1866.xlsx
Read file: 1846.xlsx
Read file: 1850.xlsx
Read file: 1893.xlsx
Read file: 1885.xlsx
Read file: 1845.xlsx
Read file: 1853.xlsx
Read file: 1890.xlsx
Read file: 1869.xlsx
Read file: 1886.xlsx
Read file: 1849.xlsx
Read file: 1873.xlsx
Read file: 1865.xlsx
Read file: 1864.xlsx
Read file: 1872.xlsx
Read file: 1848.xlsx
Read file: 1868.xlsx
Read file: 1887.xlsx
Read file: 1891.xlsx
Read file: 1852.xlsx
Read file: 1844.xlsx
Read file: 1859.xlsx
Read file: 1875.xlsx
Read file: 1863.xlsx
Read file: 1843.xlsx
Read file: 1855.xlsx
Read file: 1879.xlsx
Read file: 1896.xlsx
Read file: 1838.xlsx
Read file: 1880.xlsx
Read file: 1881.xlsx
Read file: 1839.xlsx
Read file: 1878.xlsx
Read file: 1897.xlsx
Read file: 1854.xlsx
Read file: 1842.xlsx
Read file: 1862.xlsx
Read file: 1835.xlsx
Read file: 1874.xlsx
Read file: 1858.xlsx
378726

In [4]:
print(df_census.columns)
df_census.to_csv(PROCESSED_DATA_DIR+'census_full.csv',index=False)

Index(['nom_rue', 'no_maison', 'proprietaire_nom', 'chef_prenom', 'chef_nom',
       'chef_annee_naissance', 'epouse_nom', 'epouse_annee_naissance',
       'enfants_dans_la_commune_prenom', 'enfants_annee_naissance',
       'chef_origine', 'chef_vocation', 'chef_recepisse',
       'pensionnaires_prenom', 'pensionnaires_nom',
       'pensionnaires_annee_naissance', 'pensionnaires_origine',
       'pensionnaires_condition', 'pensionnaires_recepisse', 'observations',
       'Page', 'annee', 'chef_annee_arrivee', 'proprietaire_nom_adresse',
       'chef_date_naissance_3', 'epouse_prenom', 'epouse_date_naissance_3',
       'chef_permis', 'enfants_chez_parents_prenom',
       'enfants_date_naissance_3', 'enfants_profession', 'enfants_permis',
       'pensionnaires_date_naissance_3', 'pensionnaires_permis',
       'epouse_nom_prenom', 'chef_date_naissance_1', 'epouse_date_naissance_1',
       'enfants_date_naissance_1', 'pensionnaires_date_naissance_1',
       'nom_rue_corr'],
      dtype='object')

## Keep vocation and year fields

In [18]:
df_census = pd.read_csv(PROCESSED_DATA_DIR+'census_full.csv')
df_census

/usr/local/Caskroom/miniconda/base/envs/ada/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3441: DtypeWarning: Columns (8,15,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,nom_rue,no_maison,proprietaire_nom,chef_prenom,chef_nom,chef_annee_naissance,epouse_nom,epouse_annee_naissance,enfants_dans_la_commune_prenom,enfants_annee_naissance,...,enfants_profession,enfants_permis,pensionnaires_date_naissance_3,pensionnaires_permis,epouse_nom_prenom,chef_date_naissance_1,epouse_date_naissance_1,enfants_date_naissance_1,pensionnaires_date_naissance_1,nom_rue_corr
0,grand d jean,1,bally,louis tulippel,forney,1833,celibataire,·,·,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,grand d jean,·,armurier,beat,ueteschy,1805,allamana,1809,·,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,grand d jean,·,·,francois louis,vacet|vacet,1805,cochand|lost,1810,conied|anna|marie|samson|jules|louis|julie,1834|1836|1837|1836|1839|1845|1847,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,grand d jean,2,kohler,c c ch ameace,kohler,1790,hofstottor,1800,·,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,grand d jean,·,·,c c ch ameace,·,·,·,·,·,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378721,montoye,·,vauffie,louis,stauffer,1818,mte varrin,1815,·,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378722,montoye,·,·,jn abram,sahut,ne,belley,1813,jules|ame,18431n1844e1846|1848|1850,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378723,montoye,·,·,auguste,meglan,1762,rolertine,1803,·,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378724,montoye,·,·,louis,prohy,1820,mte rey,1820,·,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378725,sevelin,·,commune,ve samuel,gyster,5184,lisabeth nigiler,1817,elise,1845e1843nee248e4950e521853eene,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df_census_reduced = df_census[['chef_vocation','enfants_profession','pensionnaires_condition','annee']].copy()
df_census_reduced.to_csv(PROCESSED_DATA_DIR+'census_reduced.csv',index=False)

In [20]:
df_census_reduced = pd.read_csv(PROCESSED_DATA_DIR+'census_reduced.csv')
df_census_reduced = df_census_reduced.fillna("")

# Replace "id" by value in row above in chef_vocation
index_id = df_census_reduced[df_census_reduced["chef_vocation"].apply(lambda s: s == "id")].index
for idx in index_id:
    df_census_reduced.loc[idx, "chef_vocation"] = df_census_reduced.loc[idx-1,"chef_vocation"]
    
df_census_reduced

,chef_vocation,enfants_profession,pensionnaires_condition,annee
0,ve de framages,,·,1861
1,journalier,,commis negociant,1861
2,caregent,,app cais negt,1861
3,gaciant trapre|louis,,pensionnaire|pensionnaire|domestique|ind,1861
4,·,,id es|id es,1861
...,...,...,...,...
378721,rentier,,·,1858
378722,journalier,,·,1858
378723,·,,·,1858
378724,fomme de lestre,,·,1858
378725,carrisseur,,·,1858

## Remove default value and separate different individual

In [21]:
def fillId(l):
    '''
    Return a list with "id" replaced by the previous term
    '''
    return_list = []
    prev = "id"
    for term in l:
        if term != "id":
            prev = term
        return_list.append(prev)
    return return_list

In [22]:
df_census_reduced = df_census_reduced.fillna("").replace('·', "") # Remove default value

# Create list form "|"-separated string of job
df_census_reduced["chef_vocation"] = df_census_reduced["chef_vocation"].str.split("|")
df_census_reduced["enfants_profession"] = df_census_reduced["enfants_profession"].str.split("|")
df_census_reduced["pensionnaires_condition"] = df_census_reduced["pensionnaires_condition"].str.split("|")
df_census_reduced = df_census_reduced.fillna("").replace('·', "") # Remove default value that emerge from split

# Fill id (=idem) field by previous job
df_census_reduced["chef_vocation"] = df_census_reduced["chef_vocation"].apply(lambda l: fillId(l))
df_census_reduced["enfants_profession"] = df_census_reduced["enfants_profession"].apply(lambda l: fillId(l))
df_census_reduced["pensionnaires_condition"] = df_census_reduced["pensionnaires_condition"].apply(lambda l: fillId(l))

In [23]:
# Merge all profession column into profession
df_census_reduced["profession"] = df_census_reduced["chef_vocation"] + df_census_reduced["enfants_profession"] + df_census_reduced["pensionnaires_condition"]
# Remove empty profession from list
df_census_reduced["profession"] = df_census_reduced["profession"].apply(lambda l: [prof for prof in l if len(prof) != 0])

In [24]:
df_census_reduced

,chef_vocation,enfants_profession,pensionnaires_condition,annee,profession
0,[ve de framages],[],[],1861,[ve de framages]
1,[journalier],[],[commis negociant],1861,"[journalier, commis negociant]"
2,[caregent],[],[app cais negt],1861,"[caregent, app cais negt]"
3,"[gaciant trapre, louis]",[],"[pensionnaire, pensionnaire, domestique, ind]",1861,"[gaciant trapre, louis, pensionnaire, pensionn..."
4,[],[],"[id es, id es]",1861,"[id es, id es]"
...,...,...,...,...,...
378721,[rentier],[],[],1858,[rentier]
378722,[journalier],[],[],1858,[journalier]
378723,[],[],[],1858,[]
378724,[fomme de lestre],[],[],1858,[fomme de lestre]
378725,[carrisseur],[],[],1858,[carrisseur]

## Reshape datastructure

In [26]:
df_job_year = df_census_reduced[["profession", "annee"]].explode("profession").copy()
df_job_year = df_job_year[~df_job_year["profession"].isin({"·", ""})]
df_job_year = df_job_year.dropna()
df_job_year

              profession  annee
0         ve de framages   1861
1             journalier   1861
1       commis negociant   1861
2               caregent   1861
2          app cais negt   1861
...                  ...    ...
378720        journalier   1858
378721           rentier   1858
378722        journalier   1858
378724   fomme de lestre   1858
378725        carrisseur   1858

[641405 rows x 2 columns]

In [50]:
df_job_by_year = df_job_year.groupby("annee")["profession"].apply(list)
print("Jobs listed by year:")
df_job_by_year

Jobs listed by year:

annee
1835    [rocureur, pensre friere se, pintier, pensre, ...
1836    [rocureur, pensionnaire, commis, di pens, pint...
1837    [vocation, comis oro, comis oro, pintier, chap...
1838    [racreur, boulanger, rintier, chapelier, pensr...
1839    [commis, commis, pensre, chal, pensionnaire, p...
                              ...
1894    [chailly venner les haper montlierond, vermand...
1895    [octave, blanche, sasa, elise, martha, louis, ...
1896    [louis, thilomine, anna, pieyse, helene, anna,...
1897    [rentiere, f mantiquane, dque, lingere, serrur...
1898    [dque, dque, marie virginie, cuisinier, tribie...
Name: profession, Length: 64, dtype: object

In [51]:
top_per_year = 100
df_count_top_by_year = df_job_by_year.apply(lambda l: Counter(l).most_common(top_per_year))

df_top_job_by_year = df_count_top_by_year.apply(lambda l: [prof for prof, count in l])
print("Most frequent jobs by year:")
df_top_job_by_year

Most frequent jobs by year:

annee
1835    [domestique, pensionnaire, ouvrier, dom, journ...
1836    [domestique, pensionnaire, rentiere, proprieta...
1837    [domestique, pensionnaire, rentiere, domestiq,...
1838    [domestique, pensionnaire, rentiere, domestiq,...
1839    [domestique, pensionnaire, rentiere, domestiq,...
                              ...
1894    [dque, menagere, rentiere, couturiere, journal...
1895    [dque, menagere, rentiere, couturiere, pensre,...
1896    [dque, menagere, rentiere, couturiere, pensre,...
1897    [domestique, menagere, dque, rentiere, couturi...
1898    [domestique, menagere, pensionnaire, rentiere,...
Name: profession, Length: 64, dtype: object

In [57]:
total_occ = len(df_job_year)
print(f"After automatic correction we keep {total_occ} job occurrences.")

top_terms = set(df_top_job_by_year.explode())
print(f"There is {len(top_terms)} distinct terms in the {top_per_year} most frequent terms by year.")

total_kept_occ = sum(df_count_top_by_year.apply(lambda l: sum([count for prof, count in l])))
print(f"After keeping only occurrences of this {len(top_terms)} distinct terms, we have {total_kept_occ} job occurrences.")
print(f"This represent {total_kept_occ / total_occ * 100}% of the occurrences.")

After automatic correction we keep 641405 job occurrences.
There is 532 distinct terms in the 100 most frequent terms by year.
After keeping only occurrences of this 532 distinct terms, we have 407409 job occurrences.
This represent 63.51821392100155% of the occurences.

In [59]:
df_jobs_1855 = pd.read_excel(DATA_DIR+"metiers_1855.xlsx", index_col=0)
df_jobs_1855["prof_norm"] = df_jobs_1855["prof_norm"].apply(lambda x: x.replace("?", ""))
jobs_1855 = set(df_jobs_1855["prof_norm"])
print(f"There is {len(jobs_1855)} corrected jobs in 1885")
jobs_1855

There is 513 corrected jobs in 1885

{"agent d'affaires",
 'agent de change',
 'agriculteur',
 'agricultrice',
 'antiquaire',
 'apprenti',
 'apprentie',
 'architecte',
 'archiviste',
 'armurier',
 'armurrier',
 'arpenteur',
 'artificier',
 'artiste',
 'artiste pedicure',
 'asphalteur',
 'assesseur',
 'aubergiste',
 'avec sa mere',
 'aveugle',
 'avocat',
 'bandagiste',
 'banquier',
 'barbier',
 'batelier',
 'bedeau',
 'belle-mere',
 'bibliothecaire',
 'bijoutier',
 'biscomier',
 'blanchisseuse',
 'boitier',
 'bordeuse',
 'bottier',
 'boucher',
 'boulanger',
 'boulangere',
 'bourrelier',
 'brasseur',
 'brodeuse',
 'brossier',
 'bucheron',
 'buraliste',
 'cafetier',
 'caissier',
 'caissier des postes',
 'capitaine de gendarmerie',
 'carrier',
 'carrossier',
 'cartier',
 'cartonnier',
 'casernier',
 'caviste',
 'chamoiseur',
 'chancelier',
 'chapelain',
 'chapelier',
 'charbonnier',
 'charcutier',
 'charpentier',
 'charpentiere',
 'charretier',
 'charron',
 'chaudronnier',
 'chauffeur',
 "chef d'institut",
 'chez m. renon',
 'chiffonniere',
 'chimiste',
 'chocolatier',
 'cigareuse',
 'cocher',
 'coiffeur',
 'colonel',
 'colporteur',
 'commis',
 'commis a la poste',
 'commis ecrivain',
 'commis negociant',
 'commissaire',
 'commissaire arpenteur',
 'commissaire de police',
 'commissaire des guerres',
 'commissaire general',
 'commission',
 'commmissaire arpenteur',
 'compositeur',
 'comptable',
 'concierge',
 'concierge des casernes',
 'conducteur',
 'confiseur',
 'confiseur patissier',
 'confiseuse',
 "conseiller d'etat",
 'conservateur',
 'constructeur',
 'controleur a la poste',
 'copiste',
 'cordier',
 'cordonnier',
 'corroyeur',
 'costille',
 'coupeur de bois',
 'courrier',
 'courrier de famille',
 'courtepointiere',
 'courtier',
 'coutelier',
 'couturiere',
 'couvreur',
 'crieur public',
 'crocheteur',
 'cuisinier',
 'cuisiniere',
 'cure',
 'daguerreotypiste',
 'de chapeaux',
 'de peine au chateau',
 'de pension',
 'de placement',
 'degrossisseur',
 'demoiselle de magasin',
 'dentiste',
 'des gendarmes',
 'directeur',
 "directeur de l'ecole normale",
 "directeur de l'instruction publique",
 'directeur de la fabrique',
 'directeur des ecoles',
 'directeur des pauvres',
 'directeur des postes',
 "directrice d'ecole",
 'dmestique',
 'domestique',
 'domestique de',
 'domestique et ouvrier',
 "domestique garcon d'ecurie",
 'domestique voiturier',
 'donander',
 'donneur de bains',
 'doreur',
 'douanier',
 'dque',
 'drapier',
 'droguiste',
 'ebeniste',
 'ecrivain',
 'ecrivain public',
 'ecuyer',
 'editeur',
 'egayeur',
 'emailleur',
 'emouleur',
 'empailleur',
 'empailleur et logeur',
 'employe',
 'employe a la banque',
 'employe au chateau',
 'employe au penitencier',
 'employe aux chemins de fer',
 'employe postal',
 'employe-chef',
 'en batiment',
 'en demeure',
 'en pension',
 'enfant naturel de louise',
 'enterreur',
 'entrepreneur',
 'epicie',
 'epicier',
 'epicier etc.',
 'equarisseur',
 'eterneur',
 'etudiant',
 'fabircant de socques',
 'fabricant',
 "fabricant d'allumettes",
 'fabricant de babouches',
 'fabricant de bas',
 'fabricant de casquettes',
 'fabricant de chandelles',
 'fabricant de chapeaux',
 'fabricant de chapeaux de paille',
 'fabricant de chauferettes',
 'fabricant de chocolat',
 'fabricant de cigares',
 'fabricant de miroirs',
 'fabricant de ouate',
 'fabricant de papier peint',
 'fabricant de parapluies',
 'fabricant de poupees',
 'fabricant de savon',
 'facteur',
 'facteur aux telegraphes',
 "facteur d'instrument",
 'facteur de lettres',
 'facteur des sels',
 'femme de chambre',
 'femme de menage',
 'ferblantier',
 'fermier',
 'fermiere',
 'fileur',
 'fileuse',
 'fille de la veuve',
 'fleuriste',
 'fondeur',
 'fontenier',
 'fontenier et entrepreneur',
 'forestier',
 'fournier',
 'fournisseur militaire',
 'fripier',
 'fripiere',
 'fruitier',
 'gagne-denier',
 'gantier',
 'gantiere',
 "garcon d'ecurie",
 'garcon de cafe',
 'garcon de place',
 'garcon voitur',
 'garcon voiturier',
 'garde champetre',
 'garde de montbenon',
 'garde fabrique',
 'garde forestier',
 'garde-malade',
 'gendarme',
 'giletiere',
 'gouvernante',
 'graveur',
 'greffier',
 'gypseur/gypsier',
 'gypseur/gypsier et vernisseur',
 'homme de menage',
 'horloger',
 'horlogere',
 'huiller',
 'huissier',
 'huissier de police',
 "huissier du conseil d'etat",
 'huissier du prefet',
 'huissier expert',
 'id',
 'imprimeur',
 'imprimeur-libraire',
 'incurable',
 'infirmier',
 'ingenieur',
 'ingenieur en chemin de fer',
 'inspecteur',
 'inspecteur des boucheries',
 'inspecteur des vignes',
 'inspecteur forestier',
 'inspecteur general des milices',
 'institut',
 'instituteur',
 'instituteur et marchand',
 'institutrice',
 'instructeur',
 'instructeur chef',
 'instructeur de trompette',
 'intendant du peage',
 'jardinier',
 'jardiniere',
 'journalier',
 'journaliere',
 'juge',
 'juge cantonal',
 "juge d'appel",
 'juge de paix',
 'laitier',
 'laitiere',
 'lampiste',
 'le mari employe',
 "le mari employe a l'hospice",
 'le mari portier',
 'le mari tailleur',
 'lessiveuse',
 'libraire',
 'limonadier',
 'lingere',
 'liquoriste',
 'lithographe',
 'locataire',
 'loge',
 'loge horloger id',
 'logeuse',
 'luthier',
 'macon',
 'macon et logeur',
 'magasinier',
 "maitre d'armes",
 'maitre de gymnase',
 'maitre de langue',
 'maitre de musique',
 'maitre de poste',
 'maitre ramoneur',
 'maitre valet',
 "maitresse d'ecole",
 'major des gendarmes',
 'manœuvre',
 'marbrier',
 'marchand',
 'marchand ambulant',
 'marchand cantinier',
 'marchand de bois',
 'marchand de bric-a-brac',
 'marchand de chevaux',
 'marchand de chiens',
 'marchand de chiffons',
 'marchand de coton',
 'marchand de fer',
 'marchand de fer et quincaillerie',
 'marchand de modes',
 'marchand de musique',
 'marchand de parapluies',
 'marchand de toiles',
 'marchand de verrerie',
 'marchand de vins',
 'marchand de volailles',
 'marchand epicier',
 'marchand papetier',
 'marchand tailleur',
 'marchand vitrier',
 'marchande',
 'marchande epiciere',
 'marchande lingere',
 'marechal',
 'marechal-ferrant',
 'marguiller',
 'matelassier',
 'mathematicien',
 'mecanicien',
 'medecin',
 'megisseur',
 'menagere',
 'menuisier',
 'menuisier et pintier',
 'messager',
 'meunier',
 'meuniere',
 'militaire',
 'mineur',
 'ministre',
 'mme epice',
 'modiste',
 'monteur de boite',
 'municipal',
 'municipal et proprietaire',
 'musee cantonal',
 'musicien',
 'musicienne',
 'negociant',
 'negociant et rentier',
 'negt tanneur',
 'notaire',
 'notaire et boursier',
 'notaire et municipal',
 'nourrice',
 'officier',
 'opticien',
 'orfevre',
 'orthopediste',
 'ouvrier',
 'ouvrier au gaz',
 'ouvrier aux chemins de fer',
 'ouvrier boucher',
 'ouvrier corroyeur',
 'ouvrier de ville',
 'ouvrier en papier peint',
 'ouvrier fondeur',
 'ouvrier gypseur',
 'ouvrier macon au chemin de fer',
 'ouvrier meunier',
 'ouvrier papetier',
 'ouvrier potier',
 'ouvriere',
 'ouvriere gantiere',
 'pailleur de chaise',
 'palefrenier',
 'papetier',
 'passementier',
 'passementiere',
 'pasteur',
 'patissier',
 'pecheur',
 'peintre',
 'pelletier',
 'pensionnair',
 'pensionnaire',
 'pensionnaire mere',
 'pensionnaires',
 'perruquier',
 'peseur',
 'pharmacien',
 'pianiste',
 'pintier',
 'pintier et logeur',
 'pintiere',
 'pionnier',
 'piqueur',
 'piquier',
 'platrier',
 'poelier',
 'polisseur',
 'porte-piano',
 'portefaix',
 'portier',
 'potier',
 "potier d'etain",
 'prefet',
 'prieur et logeur',
 'procureur',
 'procureur general',
 'professeur',
 'professeur de musique',
 'proprietaire',
 'proprietaire ',
 'proprietaire et fabricant de chandelles',
 'proprietaire et jardinier',
 'proprietaire et negociant',
 'proprietaire et rentier',
 'ramoneur',
 'receveur',
 'receveur des peages',
 'regent',
 'regente',
 'regisseur',
 'regleur',
 'relieur',
 'relieur de seilles',
 'relieur et pintier',
 'remouleur',
 'rentier',
 'rentier-pensionnaire',
 'rentiere',
 'rentiere et tient pension',
 'repasseuse',
 'repasseuse et blanchisseuse',
 'restaurateur',
 'restaurateur et aubergiste',
 's/vocation',
 'sa fille naturelle',
 'sa mere',
 'sa niece',
 'sa sœur',
 'sabotier',
 'sage-femme',
 'sans vocation',
 'sculpteur',
 'secretaire',
 'secretaire au chateau',
 'secretaire au departement militaire',
 'secretaire aux peages',
 "secretaire de l'inspecteur des milices",
 'secretaire du grand conseil',
 'secretaire du juge de paix',
 'secretaire municipal',
 'sellier',
 'sergent de gendarmerie',
 'sergent de ville',
 'sergent major de police',
 'serrurier',
 'socquier',
 'sommelier',
 'sommlier',
 'sonneur',
 'sous secretaire des ',
 'stagiaire',
 'substitut du procureur general',
 'suppleant conducteur',
 'syndic',
 'taillandier',
 'tailleur',
 'tailleur de pierre',
 'tailleur et logeur',
 'tailleur journalier',
 'tailleuse',
 'tailleuse et logeuse',
 'tanneur',
 'tapissier',
 'tapissiere',
 'teinturier',
 'teinturiere',
 'telegraphiste',
 'teneur de livre',
 'tient pension',
 'tient une ecole',
 'tier',
 'tier jardinier',
 'timbreur',
 'tisserand',
 'tonnelier',
 'tonnelier et pintier',
 'tourneur',
 'traiteur',
 'treillisseur',
 'tripier',
 'tuilier',
 'ulier',
 'urneur',
 'vannier',
 'vendeur de vin',
 'vernisseur',
 'veterinaire',
 'vigneron',
 'visiteur des morts',
 'vitrier',
 'voiturier',
 'voyer'}

In [63]:
terms_to_correct = top_terms - jobs_1855

print(f"After removing correct jobs, there is {len(terms_to_correct)} terms to check/correct")

with open('tocorrect.csv', 'w') as f:
    writer = csv.writer(f)
    for val in sorted(list(terms_to_correct)):
        writer.writerow([val])

print("Below are the terms, with their number of occurrence:")
occ_terms = df_job_year[df_job_year["profession"].isin(terms_to_correct)].groupby("profession").count()
occ_terms

After removing correct jobs, there is 385 terms to check/correct
Below are the terms, with their number of occurrence:

                 annee
profession
agent de police    438
agricult            46
agriculteur id      18
agt                 18
aide               557
...                ...
vintier             65
vocatier            20
vocation          1727
volontaire         264
vve de chambre      52

[385 rows x 1 columns]

In [65]:
occ_terms.sort_values("annee")[::-1]

            annee
profession
manoeuvre    8261
gociant      5818
pens         5402
pensre       3695
gypsier      3000
...           ...
renlier         6
merery          6
echaud          5
ailleuse        5
ordonnier       5

[385 rows x 1 columns]

In [66]:
to_correct_v1 = set(pd.read_csv(DATA_DIR+'tocorrect_v1.csv', sep=";", header = None)[0])
to_correct_v1

{'agent de police',
 'agricult',
 'agriculteur id',
 'agt',
 'aide',
 'ailleuse',
 'alire',
 'alix',
 'annee de naissance',
 'annee de naissance .',
 'ans',
 'aopriculteur',
 'app',
 'app couturiere',
 'app negociant',
 'app tailleuse',
 'apprentie modiste',
 'apprentier',
 'apprentis',
 'apprentisse',
 'arpentier',
 'atier',
 'atiere',
 'atif',
 'aypographe',
 'bauquier',
 'belmont',
 'bem',
 'ben',
 'bens',
 'berne',
 'beulanger',
 'bijoulier',
 'bingere',
 'blanchi ause',
 'bonne',
 'cafelier',
 'caiffeur',
 'catelier',
 'chapellier',
 'charon',
 'charpent',
 'charrelier',
 'chirurgien',
 'cimenteur',
 'cinturier',
 'clerc',
 'cleve',
 'clever caveug id',
 'coge',
 'commissionnaire',
 'compagne',
 'conne',
 'conseiller',
 'cord',
 'cordonier',
 'cordourier',
 'coucher',
 'cousiniere',
 'couvrent',
 'cullieateur',
 'cullisateur',
 'culottier',
 'cultivateur',
 'dam',
 'de leur recepisse',
 'de naisse',
 'del',
 'delle de magasin',
 'dem',
 'deux',
 'dgne',
 'dicelinaire',
 'diciolinaire',
 'diciphinaire id',
 'diephinaire',
 'dinier',
 'docteur',
 'dom',
 'dome',
 'domel',
 'domest',
 'domesti',
 'domestiq',
 'domestiqne',
 'domestique .',
 'domestique cleves oapheline',
 'domestique domestique',
 'domestique el regent',
 'domestique id',
 'domestique id id',
 'domestique idem',
 'domestique ouvrier',
 'domestique pensionnaire',
 'domestiques',
 'domi',
 'donnier',
 'doue',
 'dqe',
 'dqu',
 'dque dque',
 'dque id',
 'due',
 'dve',
 'e id',
 'echaud',
 'eleire',
 'elene',
 'elene aveug id',
 'eleve',
 'eleve engent',
 'eleve regent',
 'eleve regente',
 'elieur',
 'eline',
 'emp',
 'emp . a la gare',
 'emp . au chateau',
 'emp . postal',
 'emp . so .',
 'emp de banque',
 'emp j p',
 'emp j s',
 'emp so',
 'empl j s',
 'empl postal',
 'empley',
 'employe s',
 'employee',
 'employer interne',
 'en chambre',
 'enf',
 'enfant',
 'enfant naturel',
 'enft illegit',
 'enpension',
 'epalinges',
 'epiciere',
 'et',
 'etier',
 'etiere',
 'etudiant in',
 'etudiante',
 'eypographe',
 'fabriquent',
 'fait des menages',
 'felier',
 'fem de ch',
 'fem de chambre',
 'femme de ch',
 'fermiers',
 'fernier',
 'fetier',
 'fille de boutique',
 'fille de chambre',
 'fille de magasin',
 'filleuse',
 'fortier',
 'gagne denier',
 'gailleur',
 'garde de jour',
 'garde feres',
 'garde malade',
 'garde police',
 'gardinier',
 'ge',
 'gendanme',
 'gere',
 'gipier',
 'gipseur',
 'gipsier',
 'gociant',
 'gociante',
 'gondarme',
 'got',
 'gotiant',
 'gouvernant pensionnaire',
 'gre',
 'gte',
 'guisier',
 'gypseur',
 'gypsier',
 'henri',
 'henuisier',
 'hotelier',
 'ici',
 'id .',
 'id a',
 'id domestique',
 'id dque',
 'id i',
 'id id',
 'id id id',
 'id id id id',
 'id ls',
 'id n',
 'id ne aisse',
 'id nee de naisse',
 'id pensionnaire',
 'ide',
 'idem .',
 'idem domestique',
 'idemidem',
 'ideon',
 'idme',
 'idod',
 'idom',
 'idt',
 'ier',
 'ilems',
 'ineurable',
 'infirme',
 'istre',
 'jann',
 'jaque',
 'jardinier domestique',
 'jean',
 'jenny',
 'jeun',
 'jeurn',
 'jone',
 'journ',
 'journailler',
 'journaillere',
 'journaillier',
 'journailliere',
 'journal',
 'journalie',
 'journalierer',
 'journallier',
 'journalliere',
 'juge d appel',
 'julier',
 'kem',
 'la vigneron',
 'labaure',
 'laber',
 'labour',
 'laboureur',
 'laboureure',
 'laboureuse',
 'langer',
 'lans',
 'laus',
 'lausanne',
 'lavandiere',
 'lavendiere',
 'lebaureur',
 'lecheur',
 'leffiveuse',
 'lege',
 'len eogemont',
 'lessineuse',
 'leur',
 'leveregent idem',
 'lie',
 'lier',
 'linger',
 'logeur',
 'louis',
 'louise',
 'loye',
 'lque',
 'ls vocation',
 'lutry',
 'm boucher',
 'm cordonnier',
 'm de pension',
 'm jardinier',
 'm tailleur',
 'magon',
 'maitre',
 'maitresse',
 'malade',
 'manoeuvre',
 'manouvrier',
 'march',
 'marchand de vin',
 'marchde',
 'marche',
 'marchs',
 'marichal',
 'maron',
 'masson',
 'me de pension',
 'menoeuvre',
 'menrier',
 'menrinier',
 'menritier',
 'mension',
 'mere',
 'merery',
 'meron',
 'minagere',
 'monagere',
 'monnier',
 'moudon',
 'municapal',
 'munier',
 'nalade',
 'nalier',
 nan,
 'ne',
 'nee de naisse',
 'negt',
 'ni ds',
 'niculteur',
 'nier',
 'no de',
 'no de leur recepisse',
 'no des',
 'noge',
 'nsesonaire pensionnaire',
 'nuissier',
 'ordonnier',
 'orferre',
 'ounier',
 'ournalier',
 'ouv',
 'ouv charpentier',
 'ouv cordonnier',
 'ouv de ville',
 'ouv menuisier',
 'ouv serrurier',
 'ouvr macon d',
 'ouvrier di',
 'ouvrier loge',
 'ouvrier menuisier',
 'paint',
 'pare',
 'parent',
 'paul',
 'paus',
 'peint',
 'pelier',
 'penre',
 'pens',
 'pens .',
 'pens dque',
 'pensi',
 'pension',
 'pension re',
 'pensionaire',
 'pensionaire idem',
 'pensionn',
 'pensionn .',
 'pensionna',
 'pensionnai',
 'pensionnaire .',
 'pensionnaire domestique',
 'pensionnaire dque',
 'pensionnaire id',
 'pensionnaire id id',
 'pensionnaire idem',
 'pensionnaire pensionnaire',
 'pensionnat',
 'pensionne',
 'pensionnre',
 'pensionr',
 'pensionre',
 'pensre',
 'pensre .',
 'pensre de',
 'pent',
 'pentre',
 'peus',
 'pierre',
 'pilleuse',
 'pins',
 'poins',
 'point',
 'poirt',
 'pomese',
 'poprietaire',
 'potier de terre',
 'pouit',
 'pourcoucher',
 'pout',
 'prafesseur',
 'pre',
 'prietaire',
 'print',
 'profession',
 'proprietair',
 'psion',
 'pully',
 'rapes',
 'reg',
 'regis',
 'regt',
 'reguste',
 'rent',
 'rentiere .',
 'rention',
 'rentr',
 'renuisier',
 'reulier',
 'revendeuse',
 'rietaire',
 'rintier',
 'rnalier',
 'rnaliere',
 'rnsimie',
 'ront',
 'rontr',
 'roprietaire',
 's profession',
 's vocation',
 'sa fille',
 'sage femme',
 'sallieur',
 'sans',
 'sans profession',
 'sans voc',
 'sans vocat',
 'sansetta',
 'sansette',
 'saus',
 'scieur',
 'seiller',
 'seillier',
 'serrurrier',
 'servante',
 'servante ouvrier',
 'sifferand',
 'sineraud',
 'sommeiller',
 'sommeliere',
 'son domestique',
 'spocation',
 'spvocation',
 'st',
 'st cordonnier',
 'st profess',
 'st vocation',
 'ste croix idhd',
 'svocation',
 'syvocation',
 'taboureur',
 'tailleur d habits',
 'tailleur de pierres',
 'tailleure',
 'taillieur',
 'taillieus',
 'taillieuse',
 'tanneux',
 'tendeur de vin',
 'terrassier',
 'tient ecole',
 'tiere',
 'tilleur',
 'tisseraud',
 'toujours',
 'typographe',
 'une',
 'valet de chambre',
 'valteur',
 'vandeur de vin',
 'vend vin',
 'vendoin',
 'venre',
 'veudeur de vin',
 'veuve',
 'vigneron d',
 'vigneronne',
 'vintier',
 'vit de ses rentes',
 'vit de sesrenter',
 'vit de sesrentes',
 'vocatier',
 'vocation',
 'voiturier .',
 'volontaire',
 'vve de chambre'}